### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by akshetpandey** [paulfitz/daff#31]
Hey, I am facing an exception when using daff. Traceback:

```python
Traceback (most recent call last):
  File "/usr/local/bin/daff.py", line 8626, in <module>
    Coopy.main()
  File "/usr/local/bin/daff.py", line 2797, in main
    return coopy.coopyhx(io)
  File "/usr/local/bin/daff.py", line 2650, in coopyhx
    tool.saveText(output,render.render(o))
  File "/usr/local/bin/daff.py", line 2011, in saveText
    self.io.writeStdout(txt)
  File "/usr/local/bin/daff.py", line 7352, in writeStdout
    python_lib_Sys.stdout.write(txt)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 1782: ordinal not in range(128)
```

I already check and the file has no unicode characters. It is only ascii.

**Comment by paulfitz** [comment]
@akshetpandey thanks for reporting - what version of python are you seeing this with?

**Comment by paulfitz** [comment]
oh ok, I see, it is this locate issue https://pythonhosted.org/kitchen/unicode-frustrations.html - debugging.

**Comment by akshetpandey** [comment]
Python 2.7.6 on OSX 10.10.3

**Comment by paulfitz** [comment]
Does version `1.2.18` result in a change of behavior?

**Comment by akshetpandey** [comment]
Not facing this issue anymore.
