### ISSUE TITLE
Daff crashes with: UnicodeDecodeError: 'utf8'

### ISSUE THREAD

**Issue by akshetpandey** [paulfitz/daff#33]
Similar to an issue #31 I reported earlier but not the same trace.

```python
Traceback (most recent call last):
  File "/usr/local/bin/daff.py", line 8626, in <module>
    Coopy.main()
  File "/usr/local/bin/daff.py", line 2797, in main
    return coopy.coopyhx(io)
  File "/usr/local/bin/daff.py", line 2621, in coopyhx
    b = tool.loadTable(python_internal_ArrayImpl._get(args, (1 + offset)))
  File "/usr/local/bin/daff.py", line 2015, in loadTable
    txt = self.io.getContent(name)
  File "/usr/local/bin/daff.py", line 7342, in getContent
    return sys_io_File.getContent(name)
  File "/usr/local/bin/daff.py", line 8405, in getContent
    content = f.read(-1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 671, in read
    return self.reader.read(size)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by akshetpandey** [comment]
Seems to be caused because the file was accidentally saved as UTF-16...
Might be a good idea to try to detect file encoding mode before trying to decode as UTF-8.

**Comment by paulfitz** [comment]
Thanks for reporting this, and sorry for the delay responding. I looked at this and decided on balance that I can't do much better than the `UnicodeDecodeError` exception python emits without adding a new dependency or a new maintenance burden. Closing for now, will revisit if similar issues crop up.
