### ISSUE TITLE
Git Diff :: ENOENT error

### ISSUE THREAD

**Issue by Sebastien-Meiffren** [paulfitz/daff#68]
I've just installed the NPM version (1.3.17) of the app. I'm trying to run a git diff between two commits BUT I have the following error : 
```
Error: ENOENT: no such file or directory, open 'C:\Users\chuiv\PhpstormProjects\
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.tio.getContent (C:\Users\chuiv\AppData\Roaming\npm\node_modules\da
    at Object.coopy.Coopy.loadTable (C:\Users\chuiv\AppData\Roaming\npm\node_mod
    at Object.coopy.Coopy.run (C:\Users\chuiv\AppData\Roaming\npm\node_modules\d
    at Object.coopy.Coopy.coopyhx (C:\Users\chuiv\AppData\Roaming\npm\node_modul
    at run_daff_base (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\d
    at Object.exports.run_daff_main (C:\Users\chuiv\AppData\Roaming\npm\node_mod
bin\daff.js:8817:14)
fatal: external diff died, stopping at DiscountRates/Additional_parameters.csv
```

Do you know why ?

**Comment by paulfitz** [comment]
Hmm, it is dying trying to open a file, but I'm not sure why. Any chance you could get an untruncated version of that error message?  I would specifically like to see the rest of `'C:\Users\chuiv\PhpstormProjects\` to get the full filename.  Also could you let me know your `git --version`?

**Comment by Sebastien-Meiffren** [comment]
Here is the full version : 

```
$ git diff a628cd5c 5cc8d9c0
--- a/DiscountRates/Additional_parameters.csv
+++ b/DiscountRates/Additional_parameters.csv
C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:8831
                throw(e);
                ^

Error: ENOENT: no such file or directory, open 'C:\Users\chuiv\PhpstormProjects\bil-matrix\nul'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.tio.getContent (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:8650:15)
    at Object.coopy.Coopy.loadTable (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:1763:21)
    at Object.coopy.Coopy.run (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:2208:16)
    at Object.coopy.Coopy.coopyhx (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:2244:15)
    at run_daff_base (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:8782:18)
    at Object.exports.run_daff_main (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:8799:13)
    at Object.<anonymous> (C:\Users\chuiv\AppData\Roaming\npm\node_modules\daff\bin\daff.js:8817:14)
fatal: external diff died, stopping at DiscountRates/Additional_parameters.csv
```

**Comment by paulfitz** [comment]
Thanks @Sebastien-Meiffren, one more thing, could I get your `git --version`?

**Comment by Sebastien-Meiffren** [comment]
2.5.0 for Windows ... hum I feel outdated ... can this be the reason ?

**Comment by paulfitz** [comment]
Hmm checked git versions before and after that version and they appear working.  Wondering if there's something different in Windows to check.  What is the full path to `DiscountRates/Additional_parameters.csv`?  Trying to figure out how that could get garbled to `C:\Users\chuiv\PhpstormProjects\bil-matrix\nul`

**Comment by paulfitz** [comment]
Just tried Git for Windows 2.5.0, diffs worked fine for me.  Not sure what else to try.

**Comment by paulfitz** [comment]
@Sebastien-Meiffren if there are any non-ascii characters in your path, it may be worth upgrading your version of git for windows and trying again.

**Comment by Sebastien-Meiffren** [comment]
Hi,  
No none ASCII in the path.  
Full path is : C:\Users\chuiv\PhpstormProjects\bil-matrix\DiscountRates/Additional_parameters.csv

**Comment by Sebastien-Meiffren** [comment]
I just did the update, no luck => still the same :(
But thanks for your kind help
(I can't send you the files for privacy reasons)
